### ISSUE TITLE
Interesting gem

### ISSUE THREAD

**Issue by paneq** [tomichj/operate#1]
Hey, that's an interesting gem you are building :)

I just wanted to let you know that for audit trail and broadcasting (pub/sub) we use domain events in our Arkency projects.

More on that in 

* http://railseventstore.org/docs/publish/
* http://railseventstore.org/docs/subscribe/
* http://blog.arkency.com/2016/05/the-anatomy-of-domain-event/
* and in our latest book http://blog.arkency.com/domain-driven-rails/ (ps, just today we added last chapter and have a 35% discount code EVENTSOURCING ).

Have a lovely day. You can close the issue.
I didn't know a better way to contact you :)
Robert from Arkency

**Comment by tomichj** [comment]
Hi @paneq!

The pub/sub used here in operate is *very* thin, and only really used to clean up communication at the controller <-> service boundary. Other mechanisms would (obviously) also suffice: raising exceptions, for example. The intent of the gem is to aid in extracting business logic out of the controller; the pub/sub is there to make that boundary code as readable as I can manage.

Arkency's railseventstore immediately resonates with me. I've been using pub/sub for a long time to assist in DDD (even ActiveSupport::Notifications), but I've always separated the audit trail and broadcasting of events. I see the appeal of a more unified approach; thanks for the reference!

I've long been an admirer of Arkency's work, and have read a couple of your books (Fearless Refactoring, Rails meets React). You can always contact me here or on twitter: https://twitter.com/JustinTomich. Please do message me anywhere if you have any thoughts to share.

Thanks for reaching out!
